version: '3'

services:
  cloud-block-creator:
    image: node:10-buster
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
